name = "preorder-store"
pages_build_output_dir = "./public"
compatibility_date = "2026-01-01"

# Database connection (We will fill database_id in the next step)
[[d1_databases]]
binding = "DB"
database_name = "preorder-db"
database_id = b006e6d3-cae9-404f-81be-2092aa973be9

# Image Storage connection
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "preorder-images"